package com.zubajie.entity;

import java.io.Serializable;
import java.util.Date;

public class Complaint implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.complainant
     *
     * @mbg.generated
     */
    private Integer complainant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.be_complainant
     *
     * @mbg.generated
     */
    private Integer beComplainant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.is_effective
     *
     * @mbg.generated
     */
    private Byte isEffective;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column complaint.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table complaint
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.complainant
     *
     * @return the value of complaint.complainant
     *
     * @mbg.generated
     */
    public Integer getComplainant() {
        return complainant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.complainant
     *
     * @param complainant the value for complaint.complainant
     *
     * @mbg.generated
     */
    public void setComplainant(Integer complainant) {
        this.complainant = complainant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.be_complainant
     *
     * @return the value of complaint.be_complainant
     *
     * @mbg.generated
     */
    public Integer getBeComplainant() {
        return beComplainant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.be_complainant
     *
     * @param beComplainant the value for complaint.be_complainant
     *
     * @mbg.generated
     */
    public void setBeComplainant(Integer beComplainant) {
        this.beComplainant = beComplainant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.order_id
     *
     * @return the value of complaint.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.order_id
     *
     * @param orderId the value for complaint.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.time
     *
     * @return the value of complaint.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.time
     *
     * @param time the value for complaint.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.reason
     *
     * @return the value of complaint.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.reason
     *
     * @param reason the value for complaint.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.is_effective
     *
     * @return the value of complaint.is_effective
     *
     * @mbg.generated
     */
    public Byte getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.is_effective
     *
     * @param isEffective the value for complaint.is_effective
     *
     * @mbg.generated
     */
    public void setIsEffective(Byte isEffective) {
        this.isEffective = isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column complaint.score
     *
     * @return the value of complaint.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column complaint.score
     *
     * @param score the value for complaint.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", complainant=").append(complainant);
        sb.append(", beComplainant=").append(beComplainant);
        sb.append(", orderId=").append(orderId);
        sb.append(", time=").append(time);
        sb.append(", reason=").append(reason);
        sb.append(", isEffective=").append(isEffective);
        sb.append(", score=").append(score);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}