package com.zubajie.dao;

import com.zubajie.entity.AccountPassword;
import java.util.List;

public interface AccountPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_password
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_password
     *
     * @mbg.generated
     */
    int insert(AccountPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_password
     *
     * @mbg.generated
     */
    AccountPassword selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_password
     *
     * @mbg.generated
     */
    List<AccountPassword> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_password
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccountPassword record);
}