package com.zubajie.dao;

import com.zubajie.entity.Complaint;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComplaintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("complainant") Integer complainant, @Param("beComplainant") Integer beComplainant, @Param("orderId") Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated
     */
    int insert(Complaint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated
     */
    Complaint selectByPrimaryKey(@Param("complainant") Integer complainant, @Param("beComplainant") Integer beComplainant, @Param("orderId") Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated
     */
    List<Complaint> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table complaint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Complaint record);
}